### PR TITLE
lesson-1

### PR DESCRIPTION
**Pull request by Martochkaa**
I TREATED to install all the necessary programs. Created a lesson-1 branch. I tried to create the necessary files.

### CODE REVIEW

**Comment by molodkin8888** [comment]
I mentioned that we shouldn't include node_modules to git

**Review by molodkin8888 — CHANGES_REQUESTED** [review]
node_modules shouldn't be here

**Review by Dronom — CHANGES_REQUESTED** [review]
you need to add node_modules folder in gitignore

**Review by Dronom — COMMENTED** [review]
You add `"plugin:react/recommended`, but didn't specify version of React
image

**Review by Dronom — APPROVED** [review]
Looks good

**Pull request merged**
